safe:        true
markdown: kramdown
exclude: [node_modules, bower_components]
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
